server:
  port: 8080
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  http:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB

# 这里配置Hadoop
hadoop:
  fsdefault: hdfs://hzq:9000/
debug: true

